[project]
name = "l2-machine"
authors = ["your-github-username"]
description = "Decentralized Layer 2 execution environment and state management smart contract"
telemetry = false
requirements = []
[contracts.layer-two-machine]
path = "contracts/layer-two-machine.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
